# Generated by Django 5.2.6 on 2025-09-06 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_user_managers_user_date_joined_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_date',
        ),
    ]
